### ISSUE TITLE
rviz_cfg not present

### ISSUE THREAD

**Issue by t1jump** [tu-darmstadt-ros-pkg/hector_slam#13]
roslaunch hector_slam_launch tutorial.launch points to an rviz_cfg folder in the hector_slam_launch folder, but no such folder or mapping_demo.rviz file exists after install of hector_slam.

It looks like the rviz configs are present in the source version of hector_slam_launch, but aren't installed properly.

**Comment by meyerj** [comment]
This was fixed in #12.
