### ISSUE TITLE
Release for jade

### ISSUE THREAD

**Issue by hrnr** [tu-darmstadt-ros-pkg/hector_slam#19]
hector_slam is currently available for indigo. Will it be also included in jade release? It builds just fine from source on jade, but it would be nice to have it in repo.

**Comment by meyerj** [comment]
Finally: https://github.com/ros/rosdistro/pull/9781!

Check http://www.ros.org/debbuild/jade.html?q=hector_slam to see if hector_slam already found its way into the public repository...
