### ISSUE TITLE
IMU candidate for hector_imu_attitude_to_tf 

### ISSUE THREAD

**Issue by wkyoun** [tu-darmstadt-ros-pkg/hector_slam#25]
I am trying to use hector_imu_attitude_to_tf,

Would any one of you please recommend good IMU candidate to implement hector_imu_attitude_to_tf ?

(For example, IMU with already developed packages might be a good candidate)

**Comment by skohlbr** [comment]
This sounds question well suited for posting on ROS Answers. Generally, any node that produces a valid orientation in a IMU message should work. Here are some examples:
- http://wiki.ros.org/razor_imu_9dof
- http://wiki.ros.org/um7
- https://github.com/ros-drivers/microstrain_3dmgx2_imu
