### ISSUE TITLE
results are slightly different between deb and compiled node

### ISSUE THREAD

**Issue by k-okada** [tu-darmstadt-ros-pkg/hector_slam#30]
hi,

I have noticed that result of deb node and compiled node is slightly different (c.f. https://github.com/tu-darmstadt-ros-pkg/hector_slam/issues/6), it seems deb one is better. does any one   know why?

deb node:
![map-ros-binary](https://cloud.githubusercontent.com/assets/493276/17183541/f56abd7a-5462-11e6-8e77-4f7fa7da5012.png)

catkin compiled node:
![map-ros-compile](https://cloud.githubusercontent.com/assets/493276/17183556/0899bc0c-5463-11e6-9266-95317a2cbb0f.png)

**Comment by meyerj** [comment]
You already cited issue #6, which would be my first guess of what could be different. The ROS debians are built in release mode with the `-DNDEBUG` compile option, similar to cmake's `Release` or `RelWithDebInfo` build types.

Did you compile your catkin workspace with `-DCMAKE_BUILD_TYPE=Release`?

However, we could add a line to `hector_mapping/CMakeLists.txt` that sets the build type to `Release` for hector_mapping only unless set explicitly by the user.

**Comment by k-okada** [comment]
ok, I created PR to compile with optimization flag, this will generate same result for both deb and source -> https://github.com/tu-darmstadt-ros-pkg/hector_slam/pull/31
