### ISSUE TITLE
Hector mapping with RealSense R200

### ISSUE THREAD

**Issue by fw-timku** [tu-darmstadt-ros-pkg/hector_slam#38]
Hi everyone!

I am currently trying to generate a 2d map using the RealSense R200 camera from Intel. However, I have some problem building the 2d map. I am using the depth image to laser scan package from ROS to convert the depth image into a fake laser scan for the input to the hector mapping. Below is my current tf transform in the hector mapping. 
` <node pkg="tf" type="static_transform_publisher" name="map_2_base_footprint" args="0 0 0 0 0 0 /map /base_footprint 100"/> `
` <node pkg="tf" type="static_transform_publisher" name="base_footprint_2_base_link" args="0 0 0 0 0 0 /base_footprint /base_link 100"/> `
 `<node pkg="tf" type="static_transform_publisher" name="base_link_to_base_stablized" args="0 0 0 0 0 0 /base_link /base_stablized 100"/> `
`<node pkg="tf" type="static_transform_publisher" name="base_link_to_realsense" args="0 0 0.6 -1.5707963 0 -1.5707963 /base_link /realsense_frame 100" />`
`<node pkg="tf" type="static_transform_publisher" name="base_stablized_2_base_frame" args="0 0 0 0 0 0 /base_stablized /base_frame 100"/> `
 `<node pkg="tf" type="static_transform_publisher" name="base_frame_2_laser_link" args="0 0 0 0 0 0 /base_frame /camera_link 100"/>  `
`<node pkg="tf" type="static_transform_publisher" name="base_2_nav_link" args="0 0 0 0 0 0 /base_frame /nav 100"/>`  

Does the problem lie with the tf transform?

**Comment by skohlbr** [comment]
The Realsense R200 isn't well suited for use with hector_mapping due to the low FOV and different noise characteristics compared to LIDARs, so other SLAM approaches might be better suited. If still interested in the issue regardless, I suggest to post your question at https://answers.ros.org/questions/ (with more details).
