### ISSUE TITLE
Is the Hector mapping applicable for dynamic environment too?

### ISSUE THREAD

**Issue by zohaibmohammad** [tu-darmstadt-ros-pkg/hector_slam#40]
Hi,
I am trying to use Hector mapping in dynamic environment. However, both of them are showing/mapping single obstacle twice in a map (i.e. before movement and after movement). Is there any way to get latest position (after movement) of the obstacle only? 
Thanks in advance.

**Comment by zohaibmohammad** [comment]
![image](https://cloud.githubusercontent.com/assets/28756526/26155540/f65fb26a-3b2c-11e7-8177-49dbd893be29.png)


![image](https://cloud.githubusercontent.com/assets/28756526/26155563/0aa640cc-3b2d-11e7-976f-133b06f9486d.png)


Please see the attached images. Single obstacle is mapped twice by the robot while using hector mapping.

**Comment by skohlbr** [comment]
There is not explicit consideration/modeling of dynamic obstacles, but the the probabilistic map cell update will update cells according to if free or occupied space has been seen by the sensor. Default settings are not very reactive, but can be changed via the `update_factor_free` and `update_factor_occupied` parameters described here: http://wiki.ros.org/hector_mapping#Parameters

**Comment by PhehJingJie** [comment]
@engrmz Hi, may I check if you managed to implement it with Hector SLAM?

**Comment by zohaibmohammad** [comment]
> @engrmz Hi, may I check if you managed to implement it with Hector SLAM?

Hello,
I used octo-mapping for static map creation. Then I used scan matching technique for detecting dynamic object.
You can see the results in the videos here!
[https://www.youtube.com/watch?v=CByqTLxnq2o&list=PL1bGrABXHXbgfiJIb2QirOkkajmpSxXkz&index=3](url)
