### ISSUE TITLE
Qt version issue?

### ISSUE THREAD

**Issue by atyshka** [tu-darmstadt-ros-pkg/hector_slam#59]
I'm trying to compile from source on ROS Melodic and the build fails since I don't have QT4. Since Ubuntu 18.04 (and therefore Melodic) uses Qt 5, how can I get this to compile?

```
CMake Error at /usr/share/cmake-3.10/Modules/FindQt4.cmake:1320 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  hector_slam/hector_geotiff/CMakeLists.txt:12 (find_package)
```

**Comment by GabrielHuettenberger** [comment]
You can install QT 4 in melodic, using `sudo apt install qt4-default`

**Comment by rituraj-01** [comment]
As Ubuntu now uses QT5 by default, you can add QT4 to Ubuntu via third party PPA:
to install QT4-
`sudo add-apt-repository ppa:rock-core/qt4`
`sudo apt update`
`sudo apt install qt4-default`

Now you can catkin_make the hector slam package without the QT error.

**Comment by nesi73** [comment]
My environment is Ubuntu 22.04.1 and its worked for me:

`sudo add-apt-repository ppa:ubuntuhandbook1/ppa`
`sudo apt-get update`
`sudo apt-get install qt4-dev-tools libqt4-dev libqtcore4 libqtgui4`
