### ISSUE TITLE
Can Wheel Odometry be used with Hector SLAM for creating the map ?

### ISSUE THREAD

**Issue by shrijan00** [tu-darmstadt-ros-pkg/hector_slam#60]
Hi,
 I'm trying to implement Hector SLAM technique in the narrow featureless hallway/pipe. But it doesn't map since the laser scans the same at each interval. So can the wheel odometry be used along with Hector SLAM for mapping?

**Comment by skohlbr** [comment]
This would require code changes that we do not plan to implement at this time.

**Comment by elgarbe** [comment]
Hi, so it is not possible to use external odometry in order to improve the SLAM process? I found that HS lose the track in some close turns of my robot.
Thank

**Comment by Martin-Oehler** [comment]
We do not plan to implement support for odometry at this point.
