### ISSUE TITLE
Publish data pose from topic /slam_out_pose to topic /mavros/visual_position_pose

### ISSUE THREAD

**Issue by vectinaut** [tu-darmstadt-ros-pkg/hector_slam#66]
I need publish data pose of Lidar from /slam_out_pose to topic /mavros/vision_pose. How I can do this? How write node? Thanks a lot!

**Comment by Martin-Oehler** [comment]
If the message type is identical, you can simply use a [remapping](http://wiki.ros.org/roslaunch/XML/remap).

**Comment by vectinaut** [comment]
Ya, vision_pose and /slam_out pose have  identical message type (geometry_msgs/PoseStamped).

**Comment by vectinaut** [comment]
But I do not fully understand how to do it, where it is necessary to prescribe it? Can I do it in tutorial.launch?

**Comment by vectinaut** [comment]
So, I solve this problem. I use remap in mapping_default.launch
