### ISSUE TITLE
is there anything to analyze hector slam?

### ISSUE THREAD

**Issue by stmoon** [tu-darmstadt-ros-pkg/hector_slam#7]
Hi..

I have analyzed hector slam. however it is difficult for me to analyze.'
Is there any papers or technical note for analysis?

I just got one paper (a flexible and scalable SLAM system with full 3d motion estimation)

Thank you in advance

**Comment by skohlbr** [comment]
There has been some (independent) comparison to other approaches in a recent paper:

J. M. Santos, D. Portugal and R. P. Rocha - “An Evaluation of 2D SLAM Techniques Available in Robot Operating System”. In Proc. of 11th IEEE International Symposium on Safety, Security, and Rescue Robotics (SSRR 2013), Linköping, Sweden, 21-26 October, 2013.

This paper does not appear to be available online, but Chapter 4 here has the same contents: http://mrl.isr.uc.pt/archive/SmokeNav_dissertacao_Joao_Santos.pdf

Apart from the datasets we referenced and uploaded in the paper you mention above (see also https://code.google.com/p/tu-darmstadt-ros-pkg/downloads/list) we have not provided more detailed analysis so far. As performance of a SLAM system depends on a multitude of factors (environment, sensors, robot system hard&software etc.), our focus has been to make the system available for the research community and enable people to easily test it for their use case. From feedback we got, it is used on a multitude of systems including handheld systems, rescue robots, quadrotors and cars, so it is useful in a variety of applications.

If you want to perform a in-depth quantitative analysis, multiple approaches are viable for that, see for example
http://www-mip.onera.fr/annonces/CAR09/Jaulmes.pdf
http://www.informatik.uni-freiburg.de/~ki/papers/schwertfeger_et_al_permis10.pdf
http://europa.informatik.uni-freiburg.de/files/kuemmerl09auro.pdf

**Comment by stmoon** [comment]
Thank you very much !!!  :-)
