### ISSUE TITLE
Does hector_compressed_map_transport provides an image with robot location ?

### ISSUE THREAD

**Issue by shaikhalid** [tu-darmstadt-ros-pkg/hector_slam#77]
I tried but i only got map image

**Comment by l-schilling** [comment]
I'm not sure what your question is exactly. The package does not provide the robot location. If you give the package the robot location it is possible to get the map image around the robot (not the whole map)

**Comment by StefanFabian** [comment]
No as @l-schilling said, the map transport is only to send the map and you usually don't want the robot in your maps.
