### ISSUE TITLE
scale issue in map size map resolution, and slam out pose.

### ISSUE THREAD

**Issue by robbiedood** [tu-darmstadt-ros-pkg/hector_slam#80]
Dear hector_slam friends,

We are calculate position's pixel coordinator in occupancy map. It should be a simple linear transformation by using position data of /slam_out_pose, map_size, and map_resolution. However, when we draw the map and slam position on a html canvas (with the width and height as map_size), we found there is a scale issue to align occupancy map and slam position.

We were wondering if anyone have the same issue. Hope to hear your expertise.

-- Luke

**Comment by lukelu520** [comment]
problem solved. Note that pose position is NOT in normalized coordinator (doc is kind of misleading toward [0, 1]).  Therefore, pixel_coordinator = (position.x/map_reso, position.y/map_reso)
