### ISSUE TITLE
Pointcloud is not directly on the built map 

### ISSUE THREAD

**Issue by marcarroni** [tu-darmstadt-ros-pkg/hector_slam#96]
Hello everybody,

I'm new to ROS and I'm trying to deal with the hector slam. 

I tried the tutorial on http://wiki.ros.org/hector_slam/Tutorials/MappingUsingLoggedData and it also builds a map. However, I noticed that the point cloud of the laser is not directly on the map, but is constantly distributed around the entire map. This does not seem right to me, because then something is also "scanned" at the points and it should therefore also show something here.

Is this normal? I hope that you can help me. I have already worked through all the forums and unfortunately could not find a solution.

I tried to make some screenshots, that you are aware of what I'm talking about:
![Pointcloud 3](https://user-images.githubusercontent.com/82712195/116681916-e0bf4580-a9ad-11eb-8b58-873b7450759e.PNG)
![Pointcloud 2](https://user-images.githubusercontent.com/82712195/116681928-e3219f80-a9ad-11eb-9937-1260fabf3ca8.PNG)
![Pointcloud 1](https://user-images.githubusercontent.com/82712195/116681935-e4eb6300-a9ad-11eb-8fbc-b526b4b3ad0b.PNG)

**Comment by StefanFabian** [comment]
I would suggest asking these questions on ROS Answers or the robotics stackexchange.
Maybe someone from the community can help you with your problem.
We, unfortunately, do not have the resources to provide support other than addressing reproducible issues.
