### ISSUE TITLE
About playing rosbag in the tutorial

### ISSUE THREAD

**Issue by t12-kawanishi** [tu-darmstadt-ros-pkg/hector_slam#98]
I tried the tutorials on the following pages, but they didn't work.
http://wiki.ros.org/hector_slam/Tutorials/MappingUsingLoggedData

However, not ros-indigo-hector-slam
I'm using the code for the branch melodic-devel.

The parameters in the launch file are left at their defaults.

The problem is that my position doesn't change, it stays near the starting position and the map isn't created correctly.

Do I need to change any parameters?

![キャプチャ](https://user-images.githubusercontent.com/86038242/122335773-c39f0000-cf76-11eb-89d6-ab113d3f7ab4.JPG)

**Comment by wad87** [comment]
Hi, i have the same problem. how did you solve it? Have you found a solution?
